components/VerseDisplay.js

This PR adds the following: 
- Adding Scripture Reference to Scripture Pane #659
- Scripture Pane showing the wrong book #657
- ULB, verses truncated when word occurs twice #665
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/translationcoreapps/scripturepane/16)

Fixed bug  with truncated verses in the Scripture Pane #665

---

components/AddPaneModal.js
components/VerseDisplay.js

- Change Labels for Scripture Pane Content Manager #895
https://github.com/unfoldingWord-dev/translationCore/issues/895
- Made the greek pop-over disappear when clicking away #1055
https://github.com/unfoldingWord-dev/translationCore/pull/1055
- Try clicking a greek word and a pop over should open just like before but now it will close when clicking away.
- Try adding a new language to the scripture pane and the drop down menu should display the following options:
```
Instead of "Gateway Language" say "English (ULB)"
Instead of "Original Language" say "Greek (UGNT)"
Instead of "Target Language" say [whatever the name of the language is] (e.g. "Ilokano")
Instead of "UDB" say "English (UDB)"
```
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" …

changed labels for panes manager and Made the greek pop-over disappear when click away

---

components/VerseDisplay.js

Remove pipe after greek text, also removed defunct a tag for "part of speech".
Confirm that greek text is displayed without a "|" after it.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/translationcoreapps/scripturepane/34)

issue 1067, remove pipe after greek text

---

components/Pane.js
components/View.js

Addresses https://github.com/unfoldingWord-dev/translationCore/issues/1065
Load a project that is read from right to left instead of left to right. It should now properly display in the scripture pane when you select target language.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/translationcoreapps/scripturepane/36)

Fix target language direction

---

components/ExpandedPane.js
components/VerseDisplay.js

https://github.com/unfoldingWord-dev/translationCore/issues/1101
Click the button on the top right of the scripture pane. You should see the target language in the correct direction.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/translationcoreapps/scripturepane/37)

Pane Modal now shows correct direction on target language

---

components/VerseDisplay.js

Fixed the missing surrounding characters of non-current word on a multi-occurrence check in the same verse.
Fresh Titus Project, tW, God, 1:1.
Fresh Ephesians Project, tW, Body, 4:16.
Both of them have two occurrences of the same word and use to have issues, they should look good now.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/translationcoreapps/scripturepane/38)

Fixed non-current quote surrounding chars with comments

---

components/ExpandedPane.js
components/ExpandedPanesModal.js

- Scripture Pane not displaying correctly when name of translation is 2-3 lines long
Open the expanded scripture pane with a project that contains a large project name
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/translationcoreapps/scripturepane/39)

Scripture Pane now displaying correctly when name of translation is 2-3 lines long

---

components/VerseDisplay.js

Addresses QA concerns in https://github.com/unfoldingWord-dev/translationCore/issues/1101
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/translationcoreapps/scripturepane/43)

Showing verse/chapter where applicable

---

components/Pane.js

- Truncated the language header name on the scripture pane and added hover over action to display full header name
- Open a project with a long language name. 
If you cant find one just edit the manifest file 
e.g. 
```
"target_language":{"id":"fr","direction":"ltr","name":"français frança frança frança"}
```
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/translationcoreapps/scripturepane/59)

Truncated the language header name on the scripture pane

---

components/chapterView/VerseRow.js

This fixes the Chapter-view popup to show the proper language instead of the target language.
- Open any project and tool.
- Expand the Scripture Pane and ensure that it shows all the languages properly.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/translationcoreapps/scripturepane/58)

Show proper language text in chapter view

---

components/Verse.js
helpers/bibleHelpers.js
helpers/highlightHelpers.js

Scripture Pane crashes when the quote was inside another word.
Now a check is performed to ensure it's not inside another word and an actual stand alone word.
Checkout this branch in core: `bugfix/klappy/allchecks/2677` unless it's already merged.
https://github.com/unfoldingWord-dev/translationCore/files/1265442/es-419_tit_text_ulb_sav.3.zip
Import the above Titus project and tW tools.
Open the `shame` menu, and Titus 2:8.
It shouldn't throw any errors.
Find other checks and in another new Titus project to ensure the checks have the full title is in the quote.
It shouldn't throw any errors either.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/translationcoreapps/scripturepane/62)

Imporoved check for quote in verse

---

Container.js
components/Pane.js
components/Verse.js
components/WordDetails.js
helpers/lexiconHelpers.js

Replaces Greek UGNT with v0.2 and updated lexicon.
- Check out the same branch on Core
- Delete your ~/translationCore/resources folder so that launching the app populates the resources folder
- Load a Titus project, and tW, click on the Greek words in the scripture pane to get the Lexicon entries.
- Load a non-Titus project and tW, verify that the app doesn't crash but displays placeholder text.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/translationcoreapps/scripturepane/63)

Support for new UGNT v0.2 and lexicon

---

components/chapterView/VerseRow.js

This PR:
Adds place holder text to the expanded scripture pane just like the one on the regular scripture pane, to catch missing books.
Adds correct direction for the bible in the expanded scripture pane
Open the project 
[ar_eph_text_ulb.zip](https://github.com/translationCoreApps/ScripturePane/files/1323289/ar_eph_text_ulb.zip)
open the expanded scripture pane and ensure each bible has the right language direction
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/translationcoreapps/scripturepane/64)

Fixed Text Direction On Expanded Scripture Pane

---

components/Verse.js

This PR utilizes the new filtering function in the usfm module to remove extra, unneeded tags.
Checkout branch ```enhancement/jay/filter-footnotes/1941```
on Scripture Pane, and Verse Check (this is assuming the usfm latetest module with the filtering function has already been merged with develop)
and open an eph book on tN and find the check for 1:1 and ensure there are no footnotes
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/translationcoreapps/scripturepane/65)

Filtering Footnotes From Text

---

helpers/bibleHelpers.js

- Updated `UGNT` reference to `BHP`
- Delete the resources folder from the `translationCore` folder in the user directory.
- Then open a tool and you should not be able to load UGNT in the scripture pane
- This PR should be tested together with:
https://github.com/unfoldingWord-dev/translationCore/pull/2856
https://github.com/translationCoreApps/tC_Resources/pull/7
https://github.com/translationCoreApps/word-alignment-tool/pull/7
https://github.com/translationCoreApps/ScripturePane/pull/66
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/translationcoreapps/scripturepane/66)

Updated UGNT reference to BHP

---

components/Verse.js

This PR adds footnote filtering to a missing render condition.
Test project ```2 Peter tW angel/angels check```
Test project ```Php tW amen/truly```
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/translationcoreapps/scripturepane/67)

Added USFM Footnote Filtering To Missing Use Case

---

__tests__/AddPaneModal.test.js
__tests__/AddSomeTests.test.js
package-lock.json
package.json
src/components/AddPaneModal.js

Addresses issue in https://github.com/unfoldingWord-dev/translationCore/issues/2865
Go into WA and in the Scripture Pane in the top, remove a language (if already has 3) and then add a language. In the language select drop down you should now see your project's language with `(Current project)` next to it.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/translationcoreapps/scripturepane/72)

Feature - #2865 - Adds (Current project) to target language in select

---

__tests__/AddSomeTests.test.js
__tests__/ChapterViewModal.test.js
package.json
src/components/ChapterViewModal.js
src/css/Style.js

Addresses Issue https://github.com/unfoldingWord-dev/translationCore/issues/1279 for the expanded scripture pane's title
Go to tW tool for a project and expand the scripture pane at the top. It should show the name of the Bible book in the title.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/translationcoreapps/scripturepane/74)

Feature - #1279 - Adds titles to expanded scripture pane

---

src/components/Verse.js

Issue: unfoldingWord-dev/translationCore#3486
Verse.js - added skipping of punctuation in greek when loading lexicon.
Import Hebrew usfm posted here: https://github.com/unfoldingWord-dev/translationCore/issues/3486
Step through verses 1 to 7 of chapter 1.  Changes should be quick.  Also BHP and ULB panes should track the verse change.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/translationcoreapps/scripturepane/79)

Bugfix #3486/wA Tool crashes on punctuation in greek.

---

src/components/Verse.js

issue: https://github.com/unfoldingWord-dev/translationCore/issues/3543
issue: https://github.com/unfoldingWord-dev/translationCore/issues/3486
Fix issue that tries to render greek punctuation as undefined word
Select Matthew project.  In wa tool select  ch. 2:26.  Should not see undefined at beginning of greek.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/translationcoreapps/scripturepane/80)

Bugfix #3543/Fix issue that Greek punctuation renders as undefined.

---

__tests__/Verse.test.js
package-lock.json
package.json
src/components/Verse.js
src/helpers/UsfmHelpers.js

Update usfm-js that supports passing in regex to remove arbitrary USFM markers.
Now removes following USFM markers: `\q*`, `\p*`, `\s*`
Should not see markers such as `\q`, `\p`, `\s5` displayed in scripturePane
depends on https://github.com/translationCoreApps/usfm-js/pull/29
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/translationcoreapps/scripturepane/86)

Feature #3724/Extend USFM Cleaning

---

src/components/Verse.js

Verse - fixes for verseObjects displayed as resources.  If no strong's number, not clickable.  Fix spacing for quotes.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/translationcoreapps/scripturepane/90)

Feature #3188/Import Aligned EN ULB into Resources

---

__tests__/fixtures/ugnt/tit/1.json
__tests__/fixtures/ulb/tit/1.json
__tests__/highlightHelpers.test.js
src/components/Verse.js
src/helpers/highlightHelpers.js

- in tW, now matches occurrence value for UGNT and ULB in order to fix problem with double highlights of God in Titus 1:1.
- Test using: https://github.com/unfoldingWord-dev/translationCore/pull/4023
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/translationcoreapps/scripturepane/102)

Bug fix 3302/fix occurrence matching

---

src/components/Verse.js

- fixes issues that lexicon entries were not being displayed on popup initially.  This fix makes sure that they are update when component is first displayed and when content is updated.
- When you first open a project in TW, clicking on UGNT entries should show lexicon text in popup.  Click on several words to verify they have lexicon text
- then change to another group entry (left column), and again click on several words to verify they have lexicon text
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/translationcoreapps/scripturepane/104)

Bug fix 3862/missing lex entries

---

src/components/View.js

- Fixed Word Alignment opening with an error on the first project loaded after a new install 
- **Project URL to use:** https://git.door43.org/tc01/en_tit
- Delete both translationCore folders to simulate a clean install. In other words, the `translationCore` folder in the user path and the other one in the Application Support Path (The one that contains the settings.json file). 
- Import the project from the URL above.
- Load the project with the Word Alignment tool and you should not get any errors.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/translationcoreapps/scripturepane/109)

Fixed Word Alignment opening with an error on the first project loaded after a new install 

---

__tests__/stringHelpers.test.js
src/components/Verse.js
src/helpers/stringHelpers.js

- A single alignment box is displayed for verses that do not have any Greek text
- Open a project with `wordAlignment tool` that has an empty verse. 
- Go to that empty verse and a warning should display (`[WARNING: This Bible version does not include text for this reference.]`)
- Empty verses in the scripture pane should also render the same message.
- **Dependencies:**
- https://github.com/translationCoreApps/wordAlignment/pull/34
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/translationcoreapps/scripturepane/117)

A single alignment box is displayed for verses that do not have any Greek text
