AddPaneModal.js

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/translationcoreapps/scripturepane/3)

more bug fixing in the pane moadl

---

Container.js
components/Pane.js
components/View.js
css/Style.js

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/translationcoreapps/scripturepane/7)

UI update and bug fixing

---

components/CloseButton.js
components/Pane.js

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/translationcoreapps/scripturepane/8)

Added component for close button that handles changing color on hover

---

components/CloseButton.js

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/translationcoreapps/scripturepane/10)

added tooltip to remove pane button

---

components/VerseDisplay.js

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/translationcoreapps/scripturepane/12)

Fix issue for incomplete USFM files

---

components/Pane.js
components/VerseDisplay.js
components/View.js

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/translationcoreapps/scripturepane/13)

Highlights the quote in the gateway language

---

components/VerseDisplay.js

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/translationcoreapps/scripturepane/15)

Prevent the phrase from showing up in translation words

---

Container.js

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/translationcoreapps/scripturepane/17)

Scripture Pane showing the wrong book #657 and/or Target Language Doesn't Update when Loading New Project #680

---

Container.js
FetchData.js
components/AddPaneModal.js
components/View.js

relevant information in https://github.com/unfoldingWord-dev/translationCore/pull/797
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/translationcoreapps/scripturepane/19)

Added UDB to

---

Container.js
components/Pane.js
components/VerseDisplay.js
components/View.js

---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/translationcoreapps/scripturepane/21)

now using action showPopover() from new popover redux implementation 

---

css/Style.js

This PR addresses:
Not being able to see previous and next buttons due to check info card on small screens. 
Test this PR by:
On screens like Jay's, see if this adds a little more room to see previous and next buttons.
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/translationcoreapps/scripturepane/23)

Optimize heights and fonts to make a little more room for shorter screens.

---

FetchData.js

---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/translationcoreapps/scripturepane/22)

added new redux actions to fetchdata

---

Container.js
FetchData.js
components/View.js

This PR Removes the api.fetchdata calls and uses the new props given from the tool fetch data
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/translationcoreapps/scripturepane/24)

Refactor API Call Of How Tools Get Data

---

Container.js
components/Pane.js
components/VerseDisplay.js
components/View.js

Updates to get Reducer Props rendering properly
Will require updating ScripturePane, translationWords, VerseCheck to the branch of the same name: `feature/update-reducer-props`
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/translationcoreapps/scripturepane/27)

Updates to get Reducer Props rendering properly

---

components/VerseDisplay.js

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/translationcoreapps/scripturepane/28)

Addresses occurrences if there are more than one

---

components/ExpandedPane.js
components/VerseDisplay.js

---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/translationcoreapps/scripturepane/33)

removed console log from scripture pane modal

---

components/VerseDisplay.js

Now handles quotes at the beginning and end of verse.
Ephesians, translationWords check, “God” and click around through those checks. 1:4,5,9,12,22…
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/translationcoreapps/scripturepane/35)

Now handles quotes at the beginning and end of verse.

---

Container.js
components/AddBible.js
components/AddPaneModal.js
components/View.js

---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/translationcoreapps/scripturepane/40)

issue 1149, update formatting of ScripturePane

---

components/AddPaneModal.js

---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/translationcoreapps/scripturepane/41)

issue 1210, wording and formatting of add resources modal

---

components/AddBible.js
components/Pane.js

---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/translationcoreapps/scripturepane/42)

issue 1296, fix for borders

---

components/AddBible.js
components/AddPaneModal.js
components/ExpandedPane.js
components/ExpandedPanesModal.js
components/Pane.js
components/VerseDisplay.js
components/View.js
css/Style.js

---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/translationcoreapps/scripturepane/44)

issue 1408, update styling of scripture pane modals

---

components/ExpandedPanesModal.js

---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/translationcoreapps/scripturepane/45)

fix for issue 1408

---

components/View.js

---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/translationcoreapps/scripturepane/46)

Change colors

---

components/AddPaneModal.js
components/Pane.js

---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/translationcoreapps/scripturepane/47)

issue 1327, use expanded language names

---

components/AddBible.js
components/AddPaneModal.js
components/ExpandedPane.js
components/ExpandedPanesModal.js
components/Pane.js
components/View.js
css/Style.js

Added tool tips to icons and updated close buttons on modals
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/translationcoreapps/scripturepane/50)

tool tips and close buttons

---

Container.js

---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/translationcoreapps/scripturepane/51)

api removal

---

Container.js
components/View.js

---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/translationcoreapps/scripturepane/53)

bible chapter breakdown

---

Container.js
components/AddPaneModal.js
components/Pane.js
components/Verse.js
components/View.js
components/chapterView/BibleHeadingsRow.js

- Please follow instructions on
https://github.com/unfoldingWord-dev/translationCore/pull/1943
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/translationcoreapps/scripturepane/55)

made changes to accommodate new scripturepane settings implemenation

---

Container.js
components/View.js
components/chapterView/BibleHeadingsRow.js
components/chapterView/VerseRow.js

issue unfoldingWord-dev/translationCore#1989
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/translationcoreapps/scripturepane/56)

Refactor of Reducers

---

Container.js
index.js
package.json

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/translationcoreapps/scripturepane/60)

Changed the way we export the namespace and container

---

Container.js
components/Verse.js

Try to add a new bible resource to the scripture pane
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/translationcoreapps/scripturepane/61)

fixed scripture pane adding functionality

---

README.md

---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/translationcoreapps/scripturepane/71)

commit to get tools to hook

---

__tests__/Verse.test.js
package.json
src/components/Verse.js

Bugfix for issue https://github.com/unfoldingWord-dev/translationCore/issues/3198
Follow instructions in the issue to download/unzip a project and open tW (https://github.com/unfoldingWord-dev/translationCore/issues/3198)
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/translationcoreapps/scripturepane/76)

Bugfix - #3198 - Close button and Console Error when missing verse in tW

---

__tests__/Pane.test.js
__tests__/__snapshots__/Pane.test.js.snap
src/components/View.js

testing for 3210
- The unit test is in:
tC_apps/ScripturePane/__tests__/Pane.test.js
It uses a snapshot
- To test in app
- Start translationCore
- Select a project with a long language name
- Select Translation Words tool
- Resize the app by dragging app edge and hiding right panel. noticing the language name
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/translationcoreapps/scripturepane/78)

Feature bspidel 3210t

---

src/components/Pane.js
src/components/Verse.js

- Open **translationWords** and you should not get the following errors in your console.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/translationcoreapps/scripturepane/84)

Fixed bugs related to react 16

---

__tests__/Verse.test.js
src/Container.js
src/components/Pane.js
src/components/Verse.js
src/components/View.js
src/components/WordDetails.js
src/helpers/lexiconHelpers.js

Update to be compatible with verse objects and change `strongs` to `strong`.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/translationcoreapps/scripturepane/85)

Feature mcleanb #3186/use verse objects

---

src/components/Verse.js

Verse.js - added option of object for parameter verseText.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/translationcoreapps/scripturepane/87)

Bugfix #3757/Fix warning for verseText parameter

---

src/components/Verse.js

Bug fix for broken lexicon entries on verse change.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/translationcoreapps/scripturepane/89)

Bug fix #3189/broken lexicon entries on verse change

---

__tests__/Verse.test.js
package-lock.json
package.json
src/Container.js
src/components/Pane.js
src/components/Verse.js
src/components/View.js
src/components/WordDetails.js
src/helpers/UsfmHelpers.js
src/helpers/lexiconHelpers.js

Lots of USFM changes from importing to exporting to alignment data, and usage in tools.
Requires checking out branches from `translationCore`, `ScripturePane` and `WordAlignmentTool`.
Test the entire app make sure all works as intended.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/translationcoreapps/scripturepane/88)

Sandbox feature usfm3

---

.github/PULL_REQUEST_TEMPLATE.md
src/components/Verse.js

---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/translationcoreapps/scripturepane/92)

Updated PR template

---

src/components/Pane.js
src/components/chapterView/BibleHeadingsRow.js

-
-
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/translationcoreapps/scripturepane/99)

Added support for bibles new data structure that uses languageIds to organize bibles

---

package-lock.json
package.json
src/components/Verse.js

- This PR exchanges the package isEqual for deep-equal, per request of klappy from my PR regarding word alignment errors #3906.
run the following script in the root folder to get all the branches needed.
`git checkout feature-jay-3973 && git pull; cd tC_apps/ScripturePane; git checkout feature-jay-3973 && git pull; cd ../VerseCheck; git checkout feature-jay-3973 && git pull; cd ../wordAlignment; git checkout feature-jay-3973 && git pull; cd ../../;`
- Run the app and make sure everything works as expected
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/translationcoreapps/scripturepane/98)

changed isEqual to deep-equal

---

src/components/Verse.js
src/helpers/highlightHelpers.js
src/helpers/stringHelpers.js

- Fixed multiple bugs related to nested milestones
- Make sure to verify that all checks for a Titus project highlight the appropriate word in the ULB pane.
- Make sure that words are highlighting in the following checks:
- exhort, exhortation
Titus 2:15
- God
Titus 2:5
Titus 2:11
- godly, godliness
Titus 2:12
- grace, gracious
Titus 3:15
- Savior, savior
Titus 2:10
Titus 3:6
- testimony, testify
Titus 1:13
- word of God, words of God, word of Yahweh, word of the Lord, scripture, scriptures
Titus 2:5
- world, worldly
Titus 2:12
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/translationcoreapps/scripturepane/100)

Fixed multiple bugs related to nested milestones

---

src/helpers/highlightHelpers.js

-
- Make sure that checks with bible verses that have milestones don't brake word alignment tool
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/translationcoreapps/scripturepane/101)

Fixed broken word alignment tool

---

README.md

-
-
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/translationcoreapps/scripturepane/103)

This is an update to re-trigger tC webhook

---

__tests__/Pane.test.js
__tests__/__snapshots__/Pane.test.js.snap
__tests__/__snapshots__/View.test.js.snap
__tests__/fixtures/project/loadedProjectShortened.json
__tests__/highlightHelpers.test.js
__tests__/stringHelpers.test.js
src/components/Verse.js
src/helpers/highlightHelpers.js
src/helpers/stringHelpers.js

- updated UDB reference to UDT
- **Dependencies:**
- https://github.com/unfoldingWord-dev/translationCore/pull/4089
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/translationcoreapps/scripturepane/106)

updated UDB reference to UDT

---

__tests__/highlightHelpers.test.js
src/components/Verse.js
src/helpers/highlightHelpers.js

- Punctuation in the middle of a word now highlights in the Scripture Pane
- Open the following checks and verify that the punctuation is highlighted
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/translationcoreapps/scripturepane/111)

Punctuation in the middle of a word now highlights in the Scripture Pane

---

src/Container.js
src/components/Pane.js
src/components/Verse.js

- Change the non-English ULT back to ULB (In this case Hindi ULT back to ULB)
- **Dependencies:**
https://github.com/unfoldingWord-dev/translationCore/pull/4236
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/translationcoreapps/scripturepane/116)

Change the non-English ULT back to ULB (In this case Hindi ULT back to ULB)

---

index.js
package.json

Related to https://github.com/unfoldingWord-dev/translationCore/issues/4319
-
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/translationcoreapps/scripturepane/118)

updated tc-tool
